//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace Designs.Contract.First {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Web.Services.WebServiceBindingAttribute(Name="designsService", Namespace="sms.schema.designs")]
    public interface IDesignsService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/designssservice.asmx?op=addBase", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ackCode", Namespace="sms.schema.designs")]
        string addBase([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] string designDoc, [System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] int architectId);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/designssservice.asmx?op=simulate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("simulationReportDoc", Namespace="sms.schema.designs")]
        string simulate([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] int uniqueMaterialId, [System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] int uniqueDesignId, [System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] int architectId);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/designssservice.asmx?op=getDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("designDoc", Namespace="sms.schema.designs")]
        string getDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] int uniqueDesignId, [System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.designs")] int architectId);
    }
}
