<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="sms.schema.runDesignStudio"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:runDesignStudio_schema="sms.schema.runDesignStudio"
	name="runDesignStudioService"
	targetNamespace="sms.schema.runDesignStudio">
	<wsdl:types>
		<xs:schema>
			<xs:import schemaLocation="runDesignStudio.xsd" namespace="sms.schema.runDesignStudio"></xs:import>
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="StartRequest">
		<wsdl:part name="architectId" element="runDesignStudio_schema:architectId"></wsdl:part>
		<wsdl:part name="dateValue" element="runDesignStudio_schema:dateValue"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="StartResponse">
		<wsdl:part name="ackCode" element="runDesignStudio_schema:ackCode"></wsdl:part>
	</wsdl:message>

	<wsdl:portType name="runDesignStudioPortType">
	
		<wsdl:operation name="Start">
			<wsdl:input message="tns:StartRequest" name="StartRequest"></wsdl:input>
			<wsdl:output message="tns:StartResponse" name="StartResponse"></wsdl:output>
		</wsdl:operation>

	</wsdl:portType>


	<wsdl:binding name="runDesignStudioService" type="tns:runDesignStudioPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="Start">
			<soap:operation soapAction="https://localhost:44361/runDesignStudioService.asmx?op=Start" style="document"/>
			<wsdl:input name="StartRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="StartResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>

	<wsdl:service name="runDesignStudio">
		<wsdl:port binding="tns:runDesignStudioService" name="runDesignStudioPort">
			<soap:address location="http://localhost:44361/Start/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>