//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace Inventory.Contract.First {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Web.Services.WebServiceBindingAttribute(Name="inventoryService", Namespace="sms.schema.inventory")]
    public interface IInventoryService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/inventoryService.asmx?op=addItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ackCode", Namespace="sms.schema.inventory")]
        string addItem([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.inventory")] string ItemDocument);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/inventoryService.asmx?op=getItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemDocument", Namespace="sms.schema.inventory")]
        string getItem([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.inventory")] int uniqueItemId);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/inventoryService.asmx?op=getItemCount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("stockLevelValue", Namespace="sms.schema.inventory")]
        int getItemCount([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.inventory")] int uniqueItemId);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44361/inventoryService.asmx?op=removeItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ackCode", Namespace="sms.schema.inventory")]
        string removeItem([System.Xml.Serialization.XmlElementAttribute(Namespace="sms.schema.inventory")] int uniqueItemId);
    }
}
